// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXX2dHPna8O-NbaWTD7ukqSTaPVA9rdy0',
    appId: '1:1021060863316:web:a147612fd4043fe02e24c1',
    messagingSenderId: '1021060863316',
    projectId: 'cloudmessages4-2875f',
    authDomain: 'cloudmessages4-2875f.firebaseapp.com',
    storageBucket: 'cloudmessages4-2875f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10blvfmrQC51wkBymQIH4bsLyMNqnfng',
    appId: '1:1021060863316:android:f88563189b2376da2e24c1',
    messagingSenderId: '1021060863316',
    projectId: 'cloudmessages4-2875f',
    storageBucket: 'cloudmessages4-2875f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh5l3HTP14AuEnbeZEKxAJxJEXJe3Nucs',
    appId: '1:1021060863316:ios:c7c8151df61112d62e24c1',
    messagingSenderId: '1021060863316',
    projectId: 'cloudmessages4-2875f',
    storageBucket: 'cloudmessages4-2875f.appspot.com',
    iosBundleId: 'com.example.projectSem4FlutterAppMobile',
  );
}
