// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmV54qg-S0te__6-R3hWfEBZUl3CCLMoY',
    appId: '1:812381791478:web:bbfb2a05dcdf5f4f1078d7',
    messagingSenderId: '812381791478',
    projectId: 'erudite-scholar-417316',
    authDomain: 'erudite-scholar-417316.firebaseapp.com',
    storageBucket: 'erudite-scholar-417316.appspot.com',
    measurementId: 'G-3WEF7CYSBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62_13ISDGJnhFOOmxLxwonCqr2yuUlh4',
    appId: '1:812381791478:android:7dfa9fcf2b3ce4c31078d7',
    messagingSenderId: '812381791478',
    projectId: 'erudite-scholar-417316',
    storageBucket: 'erudite-scholar-417316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABv2bM_hRxG7o2I3RrkzmlPRwy446QJrU',
    appId: '1:812381791478:ios:0ece1e9bf29047ae1078d7',
    messagingSenderId: '812381791478',
    projectId: 'erudite-scholar-417316',
    storageBucket: 'erudite-scholar-417316.appspot.com',
    iosBundleId: 'com.example.projectSem4FlutterAppMobile',
  );
}
